mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_del # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
    enable-sql-runner: true # 开启 SqlRunner 以便执行原生 SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置控制台打印完整带参数SQL语句